"""Per-era P&L report on the live paper tracker.

Groups paper bets by city "era" (how long Polymarket has been pricing
temperature markets for that city). The historical backtest in commit
a8dbe59 showed that MOS edge decays as Polymarket's pricing sharpens —
London went from +$0.37/bet in 2025-H1 to -$0.24/bet in 2026-Q1, while
newly-tracked cities (Paris, Seoul, Tokyo) still held positive edge.

This script tests whether that migration pattern is playing out on the
paper tracker's live 2026-Q2 bets.

Eras are derived at runtime from data/polymarket_backtest_scored.parquet
(first-seen resolution date per city). Cities the paper tracker finds
that never appeared historically fall into `era_unknown` (typically very
newly-added).

Prints a summary; meant to be cron'd after the daily resolve job.
"""
from __future__ import annotations
import json
import sqlite3
import sys
from pathlib import Path

import pandas as pd

PROJECT = Path(__file__).resolve().parent.parent
DB = PROJECT / "data" / "weather.db"
ERAS_JSON = PROJECT / "data" / "polymarket_city_eras.json"

# Boundaries match the 2025-H1 / 2025-H2 / 2026-Q1 slices in the
# historical backtest. First-seen ≤ boundary → belongs to the bucket.
ERA_BOUNDS = [
    ("era_1_established", "2025-07-01"),  # London, NYC, Dubai: 10+ months coverage
    ("era_2_mid",         "2026-01-01"),  # Seoul: 4-10 months
    ("era_3_new",         "9999-12-31"),  # Chicago, Paris, Tokyo, etc.: <4 months
]


def city_era_map() -> dict[str, str]:
    """Load pre-computed city→era map from `polymarket_city_eras.json`.
    The JSON is generated by `make_eras_from_parquet()` and committed to
    the repo — the report itself has no parquet dependency so it runs
    under the project venv (which does not ship pyarrow).
    """
    if not ERAS_JSON.exists():
        print(f"warning: {ERAS_JSON} missing — "
              f"run polymarket_era_report.py --rebuild-eras first")
        return {}
    with open(ERAS_JSON) as f:
        return json.load(f)


def make_eras_from_parquet() -> dict[str, str]:
    """Derive city→era from data/polymarket_backtest_scored.parquet. Needs
    pyarrow so use system python or a venv with pyarrow installed. The
    output is written to polymarket_city_eras.json for the report to read.
    """
    scored = PROJECT / "data" / "polymarket_backtest_scored.parquet"
    if not scored.exists():
        print(f"error: {scored} missing — "
              f"run polymarket_historical_backtest.py first")
        sys.exit(1)
    df = pd.read_parquet(scored)
    first = df.groupby("city_raw")["resolution_date"].min()
    eras = {}
    for city, d in first.items():
        for era_name, boundary in ERA_BOUNDS:
            if d < boundary:
                eras[city] = era_name
                break
    ERAS_JSON.parent.mkdir(exist_ok=True)
    with open(ERAS_JSON, "w") as f:
        json.dump(eras, f, indent=2, sort_keys=True)
    print(f"wrote {ERAS_JSON} with {len(eras)} cities")
    return eras


def summarize(df: pd.DataFrame, label: str) -> None:
    if df.empty:
        print(f"  {label}: no rows")
        return
    n = len(df)
    flagged = int(df["would_bet_side"].notna().sum())
    resolved = int(df["resolved_yes"].notna().sum())
    pnl_rows = df[df["paper_pnl"].notna()]
    total_pnl = float(pnl_rows["paper_pnl"].sum()) if not pnl_rows.empty else 0.0
    mean_pnl = float(pnl_rows["paper_pnl"].mean()) if not pnl_rows.empty else 0.0
    wins = int((pnl_rows["paper_pnl"] > 0).sum()) if not pnl_rows.empty else 0
    hit = wins / len(pnl_rows) if not pnl_rows.empty else None
    hit_s = f"{hit*100:.1f}%" if hit is not None else "—"
    print(f"  {label:28s} n={n:4d}  flagged={flagged:3d}  resolved={resolved:3d}  "
          f"hit={hit_s}  pnl=${total_pnl:+7.2f}  mean=${mean_pnl:+.3f}")


def main() -> int:
    if "--rebuild-eras" in sys.argv:
        make_eras_from_parquet()
        return 0
    eras = city_era_map()
    if not eras:
        return 1
    conn = sqlite3.connect(str(DB))
    scan = pd.read_sql_query(
        "SELECT scan_at, target_date, city_name, city_id, event_volume_24h, "
        "bucket_label, market_yes, mos_prob, edge, would_bet_side, "
        "resolved_yes, actual_high_c, paper_pnl FROM polymarket_scan",
        conn,
    )
    if scan.empty:
        print("polymarket_scan is empty — paper tracker has not written any rows yet")
        return 0

    scan["era"] = scan["city_name"].map(eras).fillna("era_unknown")
    scan["scan_at_ts"] = pd.to_datetime(scan["scan_at"], utc=True, errors="coerce")
    latest_scan_dt = scan["scan_at_ts"].max()

    print(f"=== Polymarket paper tracker — per-era report ===")
    print(f"  source   : {DB}")
    print(f"  last scan: {latest_scan_dt}")
    print(f"  total rows: {len(scan)}  "
          f"(flagged: {int(scan['would_bet_side'].notna().sum())}  "
          f"resolved: {int(scan['resolved_yes'].notna().sum())})")
    print()

    print("=== by era ===")
    for era_name, _ in ERA_BOUNDS:
        summarize(scan[scan["era"] == era_name], era_name)
    summarize(scan[scan["era"] == "era_unknown"], "era_unknown")

    print()
    print("=== by city (bets flagged) ===")
    flagged = scan[scan["would_bet_side"].notna()].copy()
    if flagged.empty:
        print("  (none yet)")
    else:
        by_city = (flagged.groupby(["era", "city_name"])
                          .agg(n=("would_bet_side", "size"),
                               resolved=("resolved_yes", lambda s: int(s.notna().sum())),
                               pnl=("paper_pnl", "sum"))
                          .reset_index()
                          .sort_values(["era", "n"], ascending=[True, False]))
        current_era = None
        for r in by_city.itertuples(index=False):
            if r.era != current_era:
                print(f"  [{r.era}]")
                current_era = r.era
            pnl_s = f"${r.pnl:+.2f}" if pd.notna(r.pnl) else "—"
            print(f"    {r.city_name:20s} flagged={r.n:3d}  resolved={r.resolved:3d}  pnl={pnl_s}")

    print()
    print("=== by era × bet_side (pending resolution) ===")
    pending = scan[scan["would_bet_side"].notna() & scan["resolved_yes"].isna()]
    if pending.empty:
        print("  (nothing pending)")
    else:
        by = (pending.groupby(["era", "would_bet_side"]).size()
                      .rename("n").reset_index().sort_values(["era", "would_bet_side"]))
        for r in by.itertuples(index=False):
            print(f"  {r.era:28s} side={r.would_bet_side}  n={r.n}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
